// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single row in the BOM table, mapping a schematic designator to a generic part ID.
 *
 * `designator` is the reference designator on the schematic (e.g. `R1`, `C3`); it uniquely
 * identifies a component placement. `part_id` is the designer-assigned generic identifier,
 * resolved to a manufacturer part number during BOM generation.
 */
export type BomEntry = { 
/**
 * Schematic reference designator (e.g. `R1`, `C3`, `U12`). Unique within a BOM.
 */
designator: string, 
/**
 * Designer-assigned generic part identifier, resolved to a manufacturer part number at
 * BOM generation time.
 */
part_id: string, };
