// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata stored in every `.nextbom` database file.
 *
 * Describes the PCB assembly this BOM belongs to. `pcb_name` identifies the board,
 * `design_variant` distinguishes assembly variants of the same board (e.g. `"full"` vs
 * `"lite"`), and `version` is the BOM revision number.
 */
export type Metadata = { 
/**
 * Name of the PCB assembly this BOM describes.
 */
pcb_name: string, 
/**
 * Assembly variant identifier, used to distinguish builds of the same board.
 */
design_variant: string, 
/**
 * BOM revision number (e.g. `"1"`, `"2"`).
 */
bom_version: string, 
/**
 * Absolute path to the CSV file that was imported to create this BOM.
 */
source_csv_path: string, 
/**
 * Unix timestamp in milliseconds when the CSV was parsed.
 */
csv_imported_at: bigint, 
/**
 * Name of the engineer responsible for this BOM, copied from the project at import time.
 */
engineer: string, };
