// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata stored in every `.nextbom` database file.
 *
 * Describes the PCB assembly this BOM belongs to. `pcb_name` identifies the board,
 * `design_variant` distinguishes assembly variants of the same board (e.g. `"full"` vs
 * `"lite"`), and `version` is the BOM revision number.
 */
export type Metadata = { 
/**
 * Name of the PCB assembly this BOM describes.
 */
pcb_name: string, 
/**
 * Assembly variant identifier, used to distinguish builds of the same board.
 */
design_variant: string, 
/**
 * BOM revision number (e.g. `"1"`, `"2"`).
 */
version: string, };
