// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata stored in the `metadata` table of a `.nextdb` parts database.
 */
export type NextdbMetadata = { 
/**
 * User-assigned version string for this parts database.
 */
database_version: string, };
