// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project";

/**
 * Payload emitted with every `project-changed` event and returned by `get_project_state`.
 *
 * Frontend subscribers use this to keep their local state in sync after any state mutation.
 */
export type ProjectState = { 
/**
 * The currently open project, or `None` when no project is loaded.
 */
project: Project | null, 
/**
 * `true` when the in-memory project has changes that have not yet been written to disk.
 */
has_unsaved_changes: boolean, };
