// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a NextBOM project with all its properties
 */
export type Project = { 
/**
 * Unique identifier for the project (UUID v4)
 */
uuid: string, 
/**
 * Project title
 */
title: string | null, 
/**
 * Absolute path to the linked `.nextdb` parts database file
 */
database_path: string | null, 
/**
 * Name of the `alt_` table in the `.nextdb` database to append to the base `parts` table
 * during BOM generation. Entries from both tables are combined as-is in the final BOM.
 */
project_specifics: string | null, 
/**
 * Design variant identifier for this project (e.g. "full", "lite")
 */
design_variant: string | null, 
/**
 * Name of the engineer responsible for the project
 */
engineer: string | null, 
/**
 * Absolute path to the `.xlsx` file used as a BOM export template.
 * When `None`, the default blank-sheet format is used.
 */
bom_template_path: string | null, 
/**
 * Timestamp of the last change (Unix timestamp in milliseconds, UTC)
 * Updates when BOM is created, project file is modified, or any change occurs
 */
last_change: bigint, 
/**
 * Schema version, package version with which the project file was created
 */
schema: string, };
