// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a NextBOM project with all its properties
 */
export type Project = { 
/**
 * Unique identifier for the project (UUID v4)
 */
uuid: string, 
/**
 * Project title
 */
title: string | null, 
/**
 * Path to the nextbom database file
 */
database_path: string | null, 
/**
 * Identifier of the project specific parts
 */
project_specifics: string | null, 
/**
 * Design variant identifier for this project (e.g. "full", "lite")
 */
design_variant: string | null, 
/**
 * Name of the engineer responsible for the project
 */
engineer: string | null, 
/**
 * Latest BOM version string
 */
latest_bom_version: string | null, 
/**
 * Timestamp of the last change (Unix timestamp in milliseconds, UTC)
 * Updates when BOM is created, project file is modified, or any change occurs
 */
last_change: bigint, 
/**
 * Schema version, package version with which the project file was created
 */
schema: string, };
