// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a recently opened project
 */
export type RecentProject = { 
/**
 * Full path to the project file
 */
file_path: string, 
/**
 * Project title for display
 */
title: string | null, 
/**
 * Last opened timestamp (Unix timestamp in milliseconds, UTC)
 */
last_opened: bigint, };
