// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A BOM row with resolved manufacturer and MPN data, suitable for display.
 *
 * After resolution the `mfr`/`mpn` arrays are populated from the main parts database and
 * `alt_mfr`/`alt_mpn` from the project-specific alt table. Before resolution all four are
 * empty.
 */
export type ResolvedBomEntry = { designator: string, part_id: string, mfr: Array<string>, mpn: Array<string>, alt_mfr: Array<string>, alt_mpn: Array<string>, };
